export const GATE_SYLLABUS = {
  "1. Discrete Maths": ["1. Mathematical Logic", "2. Set Theory and Algebra", "3. Combinatorics", "4. Graph Theory"],
  "2. TOC": ["1. Finite Automata and Regular Languages", "2. PDA - CFL and DCFL", "3. Turing Machine, RE, REC, Undecidabilitu"],
  "3. Computer Networks": ["1. ISO-OSI Stack and SWP", "2. LAN", "3. TCP, UDP and IP", "4. Routing and Application Layer"],
  "4. COA": ["1. CPU Arch. and Address. Modes", "2. Control Unit Design", "3. Instructions Pipeline", "4. Memory Organization", "5. IO Organisation"],
  "5. Operating Systems": ["1. Process Management-1", "2. Process Management-2", "3. Deadlock", "4. Mem. Mgmt and Virtual Mem", "5. File Sys and Device Mgmt", "6. Miscellaneous"],
  "6. Data Structures": ["1. Arrays", "2. Stack and Queues", "3. Linked Lists", "4. Trees", "5. Graphs", "6. Hashing"],
  "7. Algorithms": ["1. Algo. Analysis and Asymptotic Notations", "2. Divide and Conquer", "3. Greedy Method", "4. Dynamic Programming", "5. P and NP Concepts", "6. Miscellaneous Topics"],
  "8. C Prog": ["1. Programming"],
  "9. Digital Logic": ["1. Logic Functions and Minimizations", "2. Combinational Circuits", "3. Sequential Circuits", "4. Number Systems"],
  "10. Compiler Design": ["1. Lexical Analysis", "2. Parsing Techniques", "3. Syntax Directed Translations", "4. Code Generations and Optimizatinos"],
  "11. Engg. Maths": ["1. Probability", "2. Linear Algebra", "3. Calculus"],
  "12. DBMS": ["1. ER Model", "2. Funcational Dependencies and Normalizaation", "3. Structure Query Language", "4. Relational Model", "5. Transactions and Concurrency Contorl", "6. File Structures"]
};

export const TOPIC_MAPPING = {
  "Asymptotic Notation": "1. Algo. Analysis and Asymptotic Notations",
  "Recurrence Relation": "1. Algo. Analysis and Asymptotic Notations",
  "Divide and Conquer": "2. Divide and Conquer",
  "Sorting": "2. Divide and Conquer",
  "Greedy Technique": "3. Greedy Method",
  "Minimum Spanning Tree": "3. Greedy Method",
  "Shortest Path": "3. Greedy Method",
  "Graph Traversal": "6. Miscellaneous Topics",
  "Dynamic Programming": "4. Dynamic Programming",
  "Array": "1. Arrays",
  "Link List": "3. Linked Lists",
  "Stack": "2. Stack and Queues",
  "Queue": "2. Stack and Queues",
  "Binary Tree": "4. Trees",
  "Binary Search Tree": "4. Trees",
  "AVL Tree": "4. Trees",
  "B Tree": "4. Trees",
  "B+ Tree": "4. Trees",
  "Heap Tree": "4. Trees",
  "n-ary Tree": "4. Trees",
  "Hashing": "6. Hashing",
  "Arithmetic Operation": "1. Programming",
  "Conditional Statement": "1. Programming",
  "Loops": "1. Programming",
  "Array and Pointer": "1. Programming",
  "Function": "1. Programming",
  "Lexical Analysis": "1. Lexical Analysis",
  "Parsing": "2. Parsing Techniques",
  "Syntax-directed Translation": "3. Syntax Directed Translations",
  "Intermediate Code Generation": "4. Code Generations and Optimizatinos",
  "Runtime Environment": "4. Code Generations and Optimizatinos",
  "Matching": "1. Lexical Analysis",
  "Regular Expression": "1. Finite Automata and Regular Languages",
  "Regular Grammar": "1. Finite Automata and Regular Languages",
  "Regular Language": "1. Finite Automata and Regular Languages",
  "Finite Automata": "1. Finite Automata and Regular Languages",
  "Context Free Grammar": "2. PDA - CFL and DCFL",
  "Context Free Language": "2. PDA - CFL and DCFL",
  "Push-down Automata": "2. PDA - CFL and DCFL",
  "Recursive Language": "3. Turing Machine, RE, REC, Undecidabilitu",
  "Turing Machine": "3. Turing Machine, RE, REC, Undecidabilitu",
  "Undecidability": "3. Turing Machine, RE, REC, Undecidabilitu",
  "Process": "1. Process Management-1",
  "Thread": "1. Process Management-1",
  "CPU Scheduling": "1. Process Management-1",
  "Process Synchronization": "2. Process Management-2",
  "Deadlock": "3. Deadlock",
  "Memory Management": "4. Mem. Mgmt and Virtual Mem",
  "File Systems": "5. File Sys and Device Mgmt",
  "Disk Scheduling": "5. File Sys and Device Mgmt",
  "System Call": "6. Miscellaneous",
  "OSI Layer": "1. ISO-OSI Stack and SWP",
  "Physical Layer": "1. ISO-OSI Stack and SWP",
  "Data Link Layer": "1. ISO-OSI Stack and SWP",
  "Network Layer Protocol": "3. TCP, UDP and IP",
  "Transport Layer Protocol": "3. TCP, UDP and IP",
  "Application Layer Protocols": "4. Routing and Application Layer",
  "Network Security": "4. Routing and Application Layer",
  "Machine Instruction": "1. CPU Arch. and Address. Modes",
  "Addressing Modes": "1. CPU Arch. and Address. Modes",
  "ALU Data Path and Control Unit": "2. Control Unit Design",
  "Pipeline Processor": "3. Instructions Pipeline",
  "Cache Memory": "4. Memory Organization",
  "Secondary Storage": "4. Memory Organization",
  "Memory Chip Design": "4. Memory Organization",
  "IO Interface": "5. IO Organisation",
  "Interrupt": "5. IO Organisation",
  "ER Model": "1. ER Model",
  "Normal Form": "2. Funcational Dependencies and Normalizaation",
  "SQL": "3. Structure Query Language",
  "Relational Schema": "4. Relational Model",
  "Relational Algebra": "4. Relational Model",
  "Tuple Calculus": "4. Relational Model",
  "Integrity Constraints": "4. Relational Model",
  "Transactions": "5. Transactions and Concurrency Contorl",
  "File System": "6. File Structures",
  "Propositional Logic": "1. Mathematical Logic",
  "Set Theory": "2. Set Theory and Algebra",
  "Relation": "2. Set Theory and Algebra",
  "Functions": "2. Set Theory and Algebra",
  "Lattice": "2. Set Theory and Algebra",
  "Group Theory": "2. Set Theory and Algebra",
  "Combination": "3. Combinatorics",
  "Recurrence": "3. Combinatorics",
  "Graph Theory": "4. Graph Theory",
  "Planar Graph": "4. Graph Theory",
  "Probability Theory": "1. Probability",
  "Boolean Algebra": "1. Logic Functions and Minimizations",
  "Combinational Circuit": "2. Combinational Circuits",
  "Sequential Circuit": "3. Sequential Circuits",
  "Number System": "4. Number Systems",
  "Linear Algebra": "2. Linear Algebra",
  "Calculus": "3. Calculus",
  "Numerical Method": "3. Calculus"
};

export const DEFAULT_CONFIG = {
  syllabus: GATE_SYLLABUS,
  topicMapping: TOPIC_MAPPING
};
